#!/usr/bin/env ruby

`oc login 192.168.121.135:8443 -u admin -p admin --insecure-skip-tls-verify=true`

`oc create -f templates`
`oc update -f templates`

`oc new-app --template=foreman`
`oc new-app --template=postgresql-ephemeral`
