#!/bin/bash -xe

oc login 192.168.121.135:8443 -u admin -p admin --insecure-skip-tls-verify=true

#oc new-project foreman --description="Foreman on Openshift" --display-name="The Foreman"

oc update -f templates/foreman.yaml

oc new-app --template=foreman
