#!/bin/bash

usage() {
cat <<EOF
Usage: $0 [options]

    Options:
      nightly     Run bats against nightly
      devel       Run bats against development
      content     Run content tests (yum + puppet)
      capsule     Run capsule tests (requires content)
      virt-whom   Run virt-whom candlepin tests
      swapfile    Create a 2048MB swapfile
EOF
}

[ $# -eq 0 ] && usage && exit 1

for arg do
  case $arg in
      help)
        usage
        exit 1
        ;;
      nightly)
        katello_nightly_install=true
        ;;
      content)
        katello_content_tests=true
        ;;
      virt-whom)
        katello_virt_whom=true
        ;;
      swapfile)
        swapfile=true
        ;;
      capsule)
        katello_capsule=true
        ;;
   esac
done

if [ "$katello_nightly_install" == true ];
then
    BATS_ARGS=fb-install-katello.bats
fi

if [ "$katello_content_tests" == true ];
then
    BATS_ARGS="$BATS_ARGS fb-content-katello.bats"
fi

# Must have run content suite when testing the capsule
if [ "$katello_capsule" == true ];
then
    BATS_ARGS="$BATS_ARGS fb-capsule.bats"
fi

if [ "$katello_virt_whom" == true ];
then
    BATS_ARGS="$BATS_ARGS fb-virt-whom.bats"
fi

if [ "$swapfile" == true ];
then
    # add the swapfile command to the start of the args, so it runs before tests occur
    BATS_ARGS="swapfile.bats $BATS_ARGS"
fi

cd /opt/bats

bats $BATS_ARGS fb-finish-katello.bats
