---
- include_tasks: "{{ foreman_client_repositories_environment }}_repo.yml"
  when:
    - ansible_facts['os_family'] == 'RedHat'

- name: 'Clean yum'
  command: 'yum clean all'
  tags:
    - packages
  when: ansible_facts['os_family'] == 'RedHat'
