# rubocop:disable Naming/FileName
source 'https://rubygems.org'

if RUBY_VERSION < '2.1'
  gem 'psych', '~> 2.0'
end

group :test do
  gem 'deep_merge'
  gem 'json'
  gem 'minitest'
  gem 'mocha'
  gem 'rake'
  if RUBY_VERSION < '3.1'
    # we need a rubocop that still can manage Ruby 2.0 code
    # but 0.49.x is not compatible with Ruby 3.1
    gem 'rubocop', '<0.50'
  end
end

# rubocop:enable Naming/FileName
