source 'https://rubygems.org'

group :test do
  gem 'deep_merge'
  gem 'json'
  gem 'minitest'
  gem 'mocha'
  gem 'rake'

  # Make sure the Ruby version is supported
  # https://docs.rubocop.org/rubocop/compatibility.html#support-matrix
  gem 'rubocop', '~> 1.56.0'
  gem 'rubocop-minitest'
  gem 'rubocop-performance'
  gem 'rubocop-rake'
end
