# rubocop:disable Naming/FileName
source 'https://rubygems.org'

if RUBY_VERSION < '2.1'
  gem 'psych', '~> 2.0'
end

group :test do
  gem 'deep_merge'
  gem 'json'
  gem 'minitest'
  gem 'mocha'
  gem 'rake'
  gem 'rubocop', '<0.50'
end

# rubocop:enable Naming/FileName
