---
- name: 'Setup Extra Common if Stream'
  yum:
    name: "centos-stream-repos"
    state: latest
  become: true
  tags:
    - packages
  when:
    - ansible_facts['distribution_major_version'] == '9'
    - ansible_facts['distribution'] == 'CentOS'

- name: 'Setup Epel Repository'
  yum:
    name: "{{ epel_repositories_name }}"
    disable_gpg_check: True
    state: "{{ epel_repositories_state }}"
  become: true
  tags:
    - packages
  when: ansible_facts['os_family'] == 'RedHat'
