---
- hosts: all
  vars:
    minikube_version: v1.38.0 # or latest
    multus_version: v4.2.3 # or master
  roles:
    - epel_repositories
  tasks:
    - name: install podman
      ansible.builtin.package:
        name: podman
      become: true

    - name: install minikube
      ansible.builtin.package:
        name: https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube-latest.x86_64.rpm
        disable_gpg_check: true
      become: true

    - name: install python-kubernetes
      ansible.builtin.package:
        name: python3-kubernetes
      become: true

    - name: use minikube for kubectl
      ansible.builtin.file:
        src: /usr/bin/minikube
        dest: /usr/local/bin/kubectl
        state: link
      become: true

    - name: check minikube status
      ansible.builtin.command: minikube status --output=json
      ignore_errors: true
      changed_when: false
      register: _minikube_status

    # {"Name":"minikube","Host":"Running","Kubelet":"Running","APIServer":"Running","Kubeconfig":"Configured","Worker":false}
    # will error with non-zero if no cluster defined
    - name: deploy basic minikube cluster
      ansible.builtin.command: minikube start --cni=flannel
      when: _minikube_status is failed or 'Running' not in _minikube_status.stdout

    - name: Get Cluster information
      kubernetes.core.k8s_cluster_info:
      register: _api_status

    - name: Download multus-daemonset manifest to the cluster
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/{{ multus_version }}/deployments/multus-daemonset.yml
        dest: ~/multus-daemonset.yml
        mode: '0664'

    - name: Deploy multus
      kubernetes.core.k8s:
        state: present
        src: ~/multus-daemonset.yml

    - name: deploy kubevirt
      ansible.builtin.command: minikube addons enable kubevirt
      when:
        - "'kubevirt.io/v1' not in _api_status.apis.keys()"

    - name: wait for deployment to finish
      ansible.builtin.command: !unsafe kubectl get kubevirt.kubevirt.io/kubevirt -n kubevirt --template="{{.status.phase}}"
      changed_when: false
      register: _kubevirt_status
      until: _kubevirt_status.stdout == 'Deployed'
      retries: 100

    - name: Enable HostDisk feature gate
      # https://kubevirt.io/user-guide/cluster_admin/activating_feature_gates/
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: kubevirt.io/v1
          kind: KubeVirt
          metadata:
            name: kubevirt
            namespace: kubevirt
          spec:
            configuration:
              developerConfiguration:
                featureGates:
                  - HostDisk

    - name: Create ServiceAccount foreman-account
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: foreman-account
            namespace: default

    - name: Create ClusterRoleBinding for foreman-account to get cluster-admin
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ClusterRoleBinding
          metadata:
            name: foreman-cluster-admin
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
            - kind: ServiceAccount
              name: foreman-account
              namespace: default

    - name: token
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: my-sa-token
            namespace: default
            annotations:
              kubernetes.io/service-account.name: foreman-account
          type: kubernetes.io/service-account-token

    - name: Get foreman-account secret
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: my-sa-token
        namespace: default
      register: _sa_token

    - name: Show foreman-account secret
      ansible.builtin.debug:
        msg: "{{ _sa_token.resources[0].data.token | b64decode }}"
